### ISSUE TITLE
Allow extracting of comments from an HTML document

### ISSUE THREAD

**Issue by tobstarr** [rusterlium/html5ever_elixir#121]
I wonder if there is an easy way to extract comments embedded inside an HTML document.

I tried using html5ever with Floki and using the default parser comments are present in the parsed document as 

```
{:comment, "My Comment"}
```

but when I switch the parser to html5ever they are just stripped. This can also be verified running:

```
html = """
<html><title>Some Title</title><body><!-- some comment --></body></html>
"""

Floki.parse_document(html)
|> IO.inspect()

Floki.parse_document(html, html_parser: Floki.HTMLParser.Html5ever)
|> IO.inspect()
```

that results in this output:

```
{:ok,
 [
   {"html", [],
    [{"title", [], ["Some Title"]}, {"body", [], [comment: " some comment "]}]}
 ]}
{:ok,
 [
   {"html", [],
    [{"head", [], [{"title", [], ["Some Title"]}]}, {"body", [], ["\n"]}]}
 ]}
```

**Comment by florish** [comment]
@tobstarr Thanks for opening this issue! We are using `html5ever` in a project for a while, but were not aware of HTML comments not being supported until seeing this issue.

I hope this can be fixed and I am willing to help with this, but my Rust knowledge is very limited, so I will need some guidance in orde to be able to do something.

**Comment by philss** [comment]
Hey there! Sorry for the delay. It is fixed and I saw release a new version soon.
