### ISSUE TITLE
Error during build: "Unsupported Erlang version" with OTP 22.0

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [rusterlium/html5ever_elixir#13]
```
Generated rustler app
==> html5ever
Compiling NIF crate :html5ever_nif (native/html5ever_nif)...
   Compiling erlang_nif-sys v0.6.4
   Compiling rustler_codegen v0.18.0
   Compiling syn v0.15.22
   Compiling tendril v0.4.1
error: failed to run custom build command for `erlang_nif-sys v0.6.4`
process didn't exit successfully: `/home/user/app/_build/dev/rustler_crates/html5ever_nif/release/build/erlang_nif-sys-d37b2e3dcb9ae709/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.
```

Thanks!

**Comment by Lucassifoni** [comment]
Hi,
This is now fixed in Rustler : https://github.com/rusterlium/rustler/issues/211

**Comment by hansihe** [comment]
Should be fixed in master, update publishing as soon as I get some community validation that everything is correct

**Comment by philss** [comment]
It works for me. I'm using:
- Erlang 22.0.4
- Elixir 1.9.0
- Rust 1.40.0
- html5ever from master

Thank you, @hansihe! :purple_heart:

**Comment by alessandrousseglioviretta** [comment]
works with

- Erlang 22.2.1
- Elixir 1.9.2
- Rust 1.40.0
- html5ever from master

thanks!

**Comment by fkumro** [comment]
works for me with:

Erlang 22 docker container (erlang:22)
Elixir 1.9.4
Rust 1.40.0
html5ever from master

**Comment by happysalada** [comment]
would it be a problem to release a new version with the update to close this issue?

**Comment by stevegraham** [comment]
Can confirm this works. Can you please publish a new version to hex?

**Comment by philss** [comment]
A new version was released on April 9, 2020. I'm closing the issue. Thanks to the testers! :purple_heart: 

ref: https://hex.pm/packages/html5ever/0.8.0
