### ISSUE TITLE
New release needed?

### ISSUE THREAD

**Issue by moxley** [rusterlium/html5ever_elixir#90]
Hi, I am not able to use html5ever, apparently because of a dependency issue. The latest release, 1.14.0 can only work with rustler_precompiled `~> 0.5.2`, but I'm using another package, mjml_eex, that already depends on rustler_precompiled `~> 0.6.0`. In the latest `master` branch of html5ever, it now works with rustler_precompiled `~> 0.6.0`. I configured the html5ever dependency in my mix.exs to point to `master` branch in the git repo, but when I deployed my app, it wouldn't use a precompiled NIF. Instead, it tried to compile the project with `cargo`. I then installed `cargo`, but it couldn't find the command.

Is there a step missing that normally runs when a release of html5ever is created? Is that why no precompiled NIF was found when using the `master` branch?

**Comment by philss** [comment]
Yeah, we need to release a new version! I will do in the next morning (I'm going to sleep now).

> Is there a step missing that normally runs when a release of html5ever is created? Is that why no precompiled NIF was found when using the master branch?

Yes, we need to generate the precompiled artifacts on every release. We don't do that today for the `master` branch. Only after a new release.

In any case, I will let you know here when I release the new version. Thanks for pointing out!

**Comment by moxley** [comment]
Thank you @philss! This will unblock me at the end of a very long project.

**Comment by philss** [comment]
Hey @moxley, I just released a new version. Please give it a try :)

**Comment by moxley** [comment]
Hi @philss. It's working!!! Thank you.
